apiVersion: v1
kind: Service
metadata:
  name: loki-proxy
  namespace: kafka
spec:
  type: ClusterIP
  ports:
    - port: 3100
      targetPort: 3100
  selector:
    app.kubernetes.io/name: loki  # ✅ Match this to Loki pod labels!
