apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftn-job-gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftn-job-gateway-service
  template:
    metadata:
      labels:
        app: ftn-job-gateway-service
    spec:
      nodeSelector:
        node-role: spring-app
      containers:
        - name: ftn-job-gateway-service
          image: rakeshkhopade/ftn-jobs-gateway-service:0.0.1-SNAPSHOT
          ports:
            - containerPort: 8087
          env:
            - name: SERVER_PORT
              value: "8087"
            - name: KAFKA_BROKER_URL
              value: "kafka.kafka.svc.cluster.local:9092"
            - name: JOB_TOPIC_NAME
              value: "ABCDEFG"
            - name: JOB_GATEWAYS
              value: "aws"
            - name: MANAGEMENT_SERVER_PORT
              value: "8082"
---
apiVersion: v1
kind: Service
metadata:
  name: ftn-job-gateway-service
spec:
  selector:
    app: ftn-job-gateway-service
  ports:
    - name: http-port
      port: 8087
      targetPort: 8087
    - name: http-8082
      port: 8082
      targetPort: 8082

