apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: kafka
spec:
  serviceName: kafka
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      securityContext:
        fsGroup: 1000  # Ensures correct file permissions for Kafka user
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - kafka
              topologyKey: "kubernetes.io/hostname"
      initContainers:
        - name: init-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /var/lib/kafka/data"]
          volumeMounts:
            - name: kafka-storage
              mountPath: /var/lib/kafka/data
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:latest
          env:
            - name: KAFKA_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper.kafka.svc.cluster.local:2181"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://:9092"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://$(KAFKA_POD_NAME).kafka.kafka.svc.cluster.local:9092"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "3"
            - name: KAFKA_MIN_INSYNC_REPLICAS
              value: "2"
          command: ["/bin/sh", "-c"]
          args:
            - export KAFKA_BROKER_ID=$(echo $KAFKA_POD_NAME | awk -F'-' '{print $NF}') && exec /etc/confluent/docker/run
          ports:
            - containerPort: 9092
              name: kafka
          volumeMounts:
            - name: kafka-storage
              mountPath: /var/lib/kafka/data
        - name: jmx-exporter
          image: bitnami/jmx-exporter:0.20.0
          ports:
            - containerPort: 9101
              name: metrics
          args:
            - "9101"              # Port to listen on
            - "/config/config.yml" # Path to config file
          volumeMounts:
            - name: jmx-config
              mountPath: /config  # Mount as a directory
      volumes:
        - name: jmx-config
          configMap:
            name: jmx-kafka-config
            defaultMode: 0644  # Ensure readable permissions
  volumeClaimTemplates:
    - metadata:
        name: kafka-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-storage
        resources:
          requests:
            storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: kafka
spec:
  clusterIP: None
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
  selector:
    app: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-nodeport
  namespace: kafka
spec:
  type: NodePort
  ports:
    - name: kafka-external
      port: 9092
      targetPort: 9092
      nodePort: 30992
  selector:
    app: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-metrics
  namespace: kafka
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9101
      targetPort: 9101
  selector:
    app: kafka
