apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: kafka
data:
  otel-collector-config.yaml: |
    extensions:
      health_check:
        endpoint: "0.0.0.0:13133"
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
          http:
            endpoint: "0.0.0.0:4318"
      k8s_cluster: {}
      prometheus:
        config:
          scrape_configs:
            - job_name: "kubernetes-pods"
              kubernetes_sd_configs:
                - role: pod
              relabel_configs:
                - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
                  action: keep
                  regex: "true"
                - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
                  action: replace
                  target_label: __metrics_path__
                  regex: "(.+)"
                  replacement: "$1"
                - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
                  action: replace
                  regex: (.+):(?:\d+);(\d+)
                  replacement: $1:$2
                  target_label: __address__
            - job_name: "ftn-services"
              static_configs:
                - targets:
                    - ftn-gateway-adapter.kafka.svc.cluster.local:8088
                    - ftn-job-gateway-service.kafka.svc.cluster.local:8087
                    - ftn-mobile-validator-service.kafka.svc.cluster.local:8082
                    - ftn-rule-validator-service.kafka.svc.cluster.local:8083
                    - ftn-source-io-connector.kafka.svc.cluster.local:8080
            - job_name: "kafka"
              static_configs:
                - targets:
                    - kafka-0.kafka.kafka.svc.cluster.local:9092
                    - kafka-1.kafka.kafka.svc.cluster.local:9092
                    - kafka-2.kafka.kafka.svc.cluster.local:9092
            - job_name: "zookeeper"
              static_configs:
                - targets:
                    - zookeeper-0.zookeeper.kafka.svc.cluster.local:2181
    processors:
      batch:
      resource:
        attributes:
          - action: insert
            key: k8s.namespace.name
            from_attribute: k8s.namespace
          - action: insert
            key: k8s.pod.name
            from_attribute: k8s.pod
          - action: insert
            key: k8s.service.name
            from_attribute: k8s.service
    exporters:
      otlp/jaeger:
        endpoint: "jaeger-collector.kafka.svc.cluster.local:4317"
        tls:
          insecure: true
      prometheus:
        endpoint: "0.0.0.0:8889"
      logging:
        verbosity: detailed
    service:
      extensions: [health_check]
      pipelines:
       # exporters: [otlp/jaeger]
        metrics:
          receivers: [otlp, k8s_cluster, prometheus]
          processors: [batch, resource]
          exporters: [prometheus, logging]
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging, otlp/jaeger]
