apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftn-source-io-connector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftn-source-io-connector
  template:
    metadata:
      labels:
        app: ftn-source-io-connector
    spec:
      nodeSelector:
        node-role: spring-app  # Ensures the pod runs on spring-app nodes
      containers:
        - name: ftn-source-io-connector
          image: rakeshkhopade/ftn-source-io-connector:0.0.3-SNAPSHOT
          ports:
            - containerPort: 8080
            - containerPort: 8081
            - containerPort: 9098
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: MANAGEMENT_SERVER_PORT
              value: "8082"
            - name: KAFKA_BROKER_URL
              value: "kafka.kafka.svc.cluster.local:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: ftn-source-io-connector
spec:
  type: NodePort  # Or ClusterIP if exposing through Ingress
  selector:
    app: ftn-source-io-connector
  ports:
    - name: http-port-8080
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080  # Optional: Specify or remove for dynamic allocation

    - name: http-port-8081
      protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30081

    - name: http-port-8082  # ✅ Exposing your management/actuator port!
      protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30082  # Optional: pick a unique port in the NodePort range

