apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftn-gateway-adapter
  labels:
    app: ftn-gateway-adapter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftn-gateway-adapter
  template:
    metadata:
      labels:
        app: ftn-gateway-adapter
    spec:
      nodeSelector:
        node-role: spring-app
      containers:
        - name: ftn-gateway-adapter
          image: rakeshkhopade/ftn-gateway-adapter:latest
          ports:
            - containerPort: 8088
          env:
            - name: SERVER_PORT
              value: "8088"
            - name: KAFKA_BROKER_URLS
              value: "kafka.kafka.svc.cluster.local:9092"
            - name: GATEWAY_TOPIC_NAME
              value: "ABCDEFG-aws"
            - name: MANAGEMENT_SERVER_PORT
              value: "8089"
---
apiVersion: v1
kind: Service
metadata:
  name: ftn-gateway-adapter
spec:
  selector:
    app: ftn-gateway-adapter
  ports:
    - name: http-port
      port: 8088
      targetPort: 8088
    - name: http-8089
      port: 8089
      targetPort: 8089
