allInOne:
  enabled: true
  image:
    repository: jaegertracing/all-in-one
    tag: latest
    pullPolicy: IfNotPresent
  extraEnv:
    - name: QUERY_BASE_PATH
      value: "/jaeger"  # For UI at /jaeger
provisionDataStore:
  cassandra: false
  elasticsearch: false
storage:
  type: memory
agent:
  enabled: false
collector:
  enabled: false
query:
  enabled: false
