apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftn-source-io-connector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftn-source-io-connector
  template:
    metadata:
      labels:
        app: ftn-source-io-connector
    spec:
      containers:
        - name: ftn-source-io-connector
          image: rakeshkhopade/ftn-source-io-connector:0.0.3-SNAPSHOT
          ports:
            - containerPort: 8080
            - containerPort: 8081
            - containerPort: 9098
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: MANAGEMENT_SERVER_PORT
              value: "8082"
            - name: KAFKA_BROKER_URL
              value: "kafka.kafka.svc.cluster.local:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: ftn-source-io-connector
spec:
  selector:
    app: ftn-source-io-connector
  ports:
    - name: http-port
      port: 8080
      targetPort: 8080
    - name: http-port-8081
      port: 8081
      targetPort: 8081
    - name: http-port-9098
      port: 9098
      targetPort: 9098
