---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-kafka-storage-0
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /mnt/kafka/data-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kafka-broker-id
              operator: In
              values:
                - "0"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-kafka-storage-1
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /mnt/kafka/data-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kafka-broker-id
              operator: In
              values:
                - "1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-kafka-storage-2
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /mnt/kafka/data-2
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kafka-broker-id
              operator: In
              values:
                - "2"
