apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: kafka
  labels:
    service: kafka
spec:
  serviceName: kafka
  replicas: 1
  selector:
    matchLabels:
      service: kafka
  template:
    metadata:
      labels:
        network/kafka-network: "true"
        service: kafka
    spec:
      securityContext:
        fsGroup: 1000
      enableServiceLinks: false
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.3.2  # You can specify the version you need
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9092    # External access port
            - containerPort: 29092   # Internal broker communication port
          env:
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka.kafka.svc.cluster.local:9092,INTERNAL://kafka.kafka.svc.cluster.local:29092"
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "INTERNAL"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://0.0.0.0:9092,INTERNAL://0.0.0.0:29092"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper.kafka.svc.cluster.local:2181"
            - name: KAFKA_BROKER_ID
              value: "1"  # Each broker should have a unique ID
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_DEFAULT_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"

          volumeMounts:
            - mountPath: /var/lib/kafka/
              name: kafka-data
      restartPolicy: Always
  volumeClaimTemplates:
    - metadata:
        name: kafka-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: kafka
spec:
  ports:
    - name: port-9092
      port: 9092
      targetPort: 9092
    - name: port-29092
      port: 29092
      targetPort: 29092
  selector:
    service: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-nodeport
  namespace: kafka
spec:
  type: NodePort  # Headless service for stateful set pod discovery
  ports:
    - name: kafka-external
      port: 9092
      targetPort: 9092
      nodePort: 30992
  selector:
    service: kafka
