apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  namespace: kafka
spec:
  serviceName: "zookeeper"
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      nodeSelector:
        node-role: zookeeper

      # Add initContainer here
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /var/lib/zookeeper/data /var/lib/zookeeper/log"]
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: data
              mountPath: /var/lib/zookeeper/data
            - name: log
              mountPath: /var/lib/zookeeper/log

      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:7.3.2
          ports:
            - containerPort: 2181
          env:
            - name: ZOO_4LW_COMMANDS_WHITELIST
              value: "*"
            - name: ZOOKEEPER_4LW_COMMANDS_WHITELIST
              value: "ruok,stat,mntr,conf"
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
            - name: ZOOKEEPER_SERVER_ID
              value: "1"
            - name: ZOOKEEPER_SERVERS
              value: "zookeeper:2888:3888"
            - name: KAFKA_JVM_PERFORMANCE_OPTS
              value: ""
            - name: OTEL_SERVICE_NAME
              value: "zookeeper"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector:4317"
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
            - name: OTEL_METRICS_EXPORTER
              value: "otlp"
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            privileged: true
          volumeMounts:
     #       - mountPath: /otel
    #          name: otel-agent
            - name: data
              mountPath: /var/lib/zookeeper/data
            - name: log
              mountPath: /var/lib/zookeeper/log
   #   volumes:
  #      - name: otel-agent
 #         hostPath:
#            path: /home/liberin/kafka/k8s-kafka/opentelemetry-javaagent.jar
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: standard
        resources:
          requests:
            storage: 10Gi
    - metadata:
        name: log
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: standard
        resources:
          requests:
            storage: 10Gi
