apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: kafka
spec:
  clusterIP: None  # 👈 Headless service (required for StatefulSet usually)
  ports:
    - port: 2181
      targetPort: 2181
  selector:
    app: zookeeper
