# loki-values.yml
loki:
  enabled: true
  service:
    port: 3100
    type: ClusterIP
  persistence:
    enabled: true
    size: 10Gi
    accessModes:
      - ReadWriteOnce
    storageClassName: <your-storage-class>  # Replace with `kubectl get sc` output, e.g., "standard"
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
      - host: loki.your-domain.com
        paths:
          - "/"  # Simplified to a string, chart should default pathType to Prefix
    tls: []

promtail:
  enabled: true
  config:
    clients:
      - url: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push
    snippets:
      scrapeConfigs: |
        - job_name: kafka-pods
          pipeline_stages:
            - cri: {}
          kubernetes_sd_configs:
            - role: pod
              namespaces:
                names:
                  - kafka
          relabel_configs:
            - source_labels: [__meta_kubernetes_pod_controller_name]
              regex: ([0-9a-z-.]+?)(-[0-9a-f]{8,10})?
              action: replace
              target_label: __tmp_controller_name
            - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name, __meta_kubernetes_pod_label_app, __tmp_controller_name, __meta_kubernetes_pod_name]
              regex: ^;*([^;]+)(;.*)?$
              action: replace
              target_label: app
            - source_labels: [__meta_kubernetes_namespace]
              action: replace
              target_label: namespace
            - source_labels: [__meta_kubernetes_pod_name]
              action: replace
              target_label: pod
            - source_labels: [__meta_kubernetes_pod_container_name]
              action: replace
              target_label: container
            - source_labels: [__meta_kubernetes_pod_uid, __meta_kubernetes_pod_container_name]
              separator: /
              action: replace
              replacement: /var/log/pods/*$1/*.log
              target_label: __path__

filebeat:
  enabled: false
fluent-bit:
  enabled: false
grafana:
  enabled: false
logstash:
  enabled: false
prometheus:
  enabled: false
