#apiVersion: v1
#kind: Service
#metadata:
#  name: loki-proxy
 # namespace: kafka
#spec:
 # type: ExternalName
 # externalName: loki.monitoring.svc.cluster.local
apiVersion: v1
kind: Service
metadata:
  name: loki-proxy
  namespace: kafka
spec:
  type: ClusterIP
  ports:
    - port: 3100
      targetPort: 3100
  selector:
    app: loki  # Make sure Loki pods have this label in the "monitoring" namespace
