apiVersion: v1
kind: Service
metadata:
  name: otel-collector-service
  namespace: opentelemetry
spec:
  selector:
    app.kubernetes.io/name: opentelemetry-collector
  ports:
    - name: grpc
      port: 4317
      targetPort: 4317
    - name: http
      port: 4318
      targetPort: 4318
    - name: metrics
      port: 8888
      targetPort: 8888
  type: ClusterIP
