apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data-zookeeper
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  local:                               # ✅ Replace hostPath with local
    path: "/mnt/data/zookeeper"        # ✅ Same directory
  nodeAffinity:                        # ✅ Add this!
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - e2e-118-192          # ✅ Your zookeeper node hostname
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-log-zookeeper
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  local:
    path: "/mnt/log/zookeeper"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - e2e-118-192
